language: python

python:
  - "3.6"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - pip install django coverage coveralls
  - cd frontend && npm install && npm install coveralls && cd ..

before_script:
  - cd backend && python manage.py migrate && cd ..

script:
  - cd backend && coverage run --branch manage.py test && cd ..
  - cd frontend && ng test --coverage --watch false && ng e2e && cd ..

after_success:
  - coveralls
  - cat ./frontend/coverage/lcov.info | ./frontend/node_modules/coveralls/bin/coveralls.js
